internal/gke/babysitter.go, internal/local/babysitter.go
This will allow us to remove the code from the envelope for restarting the weavelet.
After this change, the GKE deployer will restart the babysitter jobs automatically, whenever the weavelet fails. For GKE local, no restarts will happen. (This should probably be changed in a future change.)
=> Don't create the envelope with retry options for GKE deployers.

go.mod, go.sum, internal/gke/deploy.go, internal/gke/gke.go, internal/gke/kube_patcher.go
This allows the kubernetes control plane to issue certificates to the Service Weaver's running pods.
=> Setup the certificate authorities in user's project.

cmd/weaver-gke-local/main.go, cmd/weaver-gke/main.go, go.mod, go.sum
This PR introduces "weaver gke version" and "weaver gke-local version" commands. See https://github.com/ServiceWeaver/weaver/pull/220 for context on version commands.
```console
$ weaver gke version
weaver gke: commit=aaef22370b9f511f896b249d2b45094f4849e37c deployer=v0.2.0 target=linux/amd64
$ weaver gke-local version
weaver gke-local: commit=aaef22370b9f511f896b249d2b45094f4849e37c deployer=v0.2.0 target=linux/amd64
```
=> Added gke and gke-local version subcommands.

internal/gke/deploy.go, internal/gke/metrics.go
This has suddenly started being enforced on GKE.
=> Specify metric labels when creating a metric descriptor.

internal/gke/deploy.go
Namely:
* Enable the Cloud Tracing API.
* Fix vertical pod autoscaler to only scale up memory.
The latter was done in order to avoid vertically scaling up CPU beyond the capacity of the underlying VM. (We believe the default used to be memory-based-scaling only, which is why we're seeing these issues only now.)
=> More GKE fixes.

internal/gke/cloud_config.go, internal/gke/deploy.go
The bug was caused by the newer gcloud version, which now requires (and supports) the "--location" flag when creating a new memberhsip binding. These bindings no longer default to the "global" location, resulting in regional fleet memberships.
While at it, check the gcloud version before starting a deployment, and encourage users to update the gcloud to the latest version.
=> Fix the fleet registration bug.

internal/gke/kubestore.go, internal/tool/store.go
This PR introduces a `weaver gke store purge` command that purges all store entries from a kubestore. This is a small step towards implementing a `weaver gke purge` command that will purge everything.
=> Added "weaver gke store purge" command.

internal/gke/build.go, internal/gke/deploy.go
Previously, we would always use the `@latest` tool version, which leads to compatibility issues. This change ensures that the user runs the same tool version locally and inside the cloud.
Other changes:
* Simplify Go builds using the separate image to do the builds. This was suggested by one of the contributors for the
weaver-kube repository.
=> When cross-compiling, use the same tool version as on local machine.

internal/gke/build.go, internal/gke/deploy.go, internal/tool/deploy.go
Namely:
* Disable build logging to storage buckets, as it requires extra permissions.
* Enable an additional cloud service api (service usage).
* Acquire controller address only after the config cluster has been created. (d'oh).
=> A couple of GKE-related fixes.

internal/local/certs_test.go, internal/local/tool.go
This race was introduced by a recent change where we changed the order of calls to `Controller` and `PrepareRollout` while deploying. This introduced a known race where the controller and the tool attempt to create and store the shared CA certificate key on the local file system. In turn, this caused the tool and the controller to use different CA certificates, resulting in a TLS error between them.
This change restores the old behavior of the tool generating the CA certificate before starting the controller.
Other changes:
* Add a simple test for certificates (unrelated to this fix).
=> Fix a race in creating CA certificate/key between tool and controller.

internal/gke/babysitter.go, internal/version/version.go
This fixes the endpoint health-checks that are currently failing at the assigner.
=> Don't report localhost addresses on GKE. (d'oh)

.github/workflows/integration.yml, examples/echo/weaver.toml, go.mod, go.sum, internal/babysitter/babysitter.go, internal/gke/babysitter.go, internal/gke/deploy.go, internal/gke/gke.go, internal/local/babysitter.go, internal/local/cond/cond.go, internal/local/cond/cond_test.go, internal/local/nanny.go, internal/local/starter.go
This change mimics the related change in weaver-kube where the babysitter watches the activated component's pods and returns the replicas therein. The GKE deployer was previously consulting the assigner for an updated set of replicas, which is a complicated flow fraught with possibilities of errors.
Moreover, an upcoming weaver change will see weavelets performing health checks themselves, obsoleting the current GKE mechanism which has the assigner performing health checks on the babysitters.
TODO: Change the assigner to only manage routing information for routed components.
Other changes:
* Fix labeling for all resources to produce values that are guaranteed DNS labels (e.g., replica sets often aren't).
* Minor code fixes.
=> Use the Pod watcher to detect the set of remote component replicas.

.github/workflows/integration.yml, internal/gke/cloud_patcher.go, internal/gke/deploy.go, internal/gke/gke.go, internal/gke/kube_patcher.go
Namely:
* Use a Kubernetes Role instead of a ClusterRole. The former is namespace-scoped, so it fits our use-case better.
* Don't create a Role per component. Instead, create a single "application" role and use it across the components.
* Explicitly specify deletion permissions for rolebindings, as using the "*" doesn't seem to work for some reason.
The above changes, in addition to being more sensible, also fix the cleanup issue where the deletion of older version was failing.
=> A few permissions-related changes.

.github/workflows/integration.yml, examples/echo/echo.go
Currently, GCP has a rather small default limit on the number of SSL certificates it can maintain. Additionally, we don't have a good way of deleting certificates when they are no longer needed. For this reason, we temporarily reduce the number of certificates by reusing the same hostname in integration tests, namely, "echo.serviceweaver.dev".
We will implement correct certificate deletion in a future change.
=> Use the same hostname for all versions of the echo app.

internal/gke/deploy.go
Previously, we weren't creating identity for a weaver.Main iff it was the only component in the application binary.
=> Ensure we create identity for the main component.

cmd/weaver-gke-local/version.go, cmd/weaver-gke/version.go, internal/gke/deploy.go, internal/gke/version.go
This simplifies the release process as it removes the redundant version tracking we used to do manually. It also means versions can be more fine-grained (e.g., at the github commit level).
=> Change the tool to read the version information from the running binary.

cmd/weaver-gke-local/controller.go, cmd/weaver-gke-local/distributor.go, cmd/weaver-gke-local/manager.go, cmd/weaver-gke-local/proxy.go, internal/babysitter/logger.go, internal/local/nanny.go, internal/local/tool.go
Previously the sub-processes created for the GKE local deployment would discard stdout and stderr messages. This made it really hard to debug problems (e.g., panic messages would get lost). We now capture lines written to stdout and stderr by these sub-processes and write them to log storage.
Removed a stray "LogBatch" stderr message from a previous change.
Example output after killing a controller process by hand:
```
Tailing the logs...
S1004 13:05:55.316463 stdout               d9a66407                      │ echo listener available on http://localhost:8000
S1004 13:05:55.326168 stdout               3826452b                      │ echo listener available on http://localhost:8000
S1004 13:06:13.219034 controller.stdout    65f17a29                      │ sub-process read error err="EOF" …
```
=> Capture GKE local sub-process stderr and stdout.

internal/gke/build.go
This is required as we no longer support Go 1.20.
=> Use Go 1.21 when building the tool image inside the container.

internal/gke/deploy.go
This (hopefully) solves the issue of nanny jobs' reachability from external clusters.
=> Specify open ports for nanny jobs explicitly in the container.

internal/tool/status.go
The `weaver-gke` status or `weaver-gke-local` status display the rollout start time in UTC. This is confusing and misleading.
This PR ensure that the time is displayed in local timezone.
=> Display the rollout time in local timezone

.github/workflows/integration.yml, internal/gke/cloud_config.go, internal/gke/cmd.go
Users may want to deploy apps in different cloud projects than the one they are currently logged in (gcloud init). The current GKE implementation has a bug that prevents them to do this. Most of the gcloud commands don't take a `--project` and an `--account` argument, and the gcloud command will consider the project and the account values as the ones set in the current project.
E.g.,
Current project is `psyched-zone-398223`, and I tried to deploy an app in the project `dingo-gke-dev`. This is what the current GKE deployer does:
`
rgrandl@:~/projects/weaver_wip/weaver-gke$ ./cmd/weaver-gke/weaver-gke deploy --project="dingo-gke-dev" ../weaver/examples/collatz/weaver.toml Deploying to project dingo-gke-dev
Starting the application container build …
=> [GKE] Enable to deploy in a different project

cmd/weaver-gke/store.go, internal/gke/cluster_info.go, internal/gke/deploy.go, internal/gke/gke.go, internal/gke/logging.go, internal/gke/nanny.go, internal/gke/purge.go, internal/tool/deploy.go, internal/tool/deploy_test.go
In the current implementation, the GKE deployer creates a cluster for each region where the application is being deployed. Also, it creates a config cluster in "us-central1" where the controller is being deployed.
This is not great, because for each user project, we create an additional cluster which translates into cloud costs for the user.
This PR deploys the controller in one of the clusters where applications that are part of the same user project are being deployer.
If this is the first time the user deploys an app in their project, the controller is deployed in the first region where the app is being deployed. However, if the controller is already running in some cluster, it will run there forever.
The caveat with this approach is that if the user decides some day to not deploy …
=> Don't create special config cluster.

internal/gke/deploy.go, internal/gke/gke.go, internal/gke/purge.go
We changed the way we deploy the Service Weaver config cluster; i.e., we deploy the controller in one of the application clusters instead.
However, for old deployments, the user might still have the config cluster (that runs in us-central1) around.
This PR updates the purge command to delete the us-central1 config cluster as well (if exists).
=> Purge the deprecated config cluster

internal/babysitter/client.go, internal/gke/babysitter.go, internal/gke/nanny.go, internal/local/babysitter.go, internal/local/nanny.go, internal/nanny/distributor/client.go, internal/nanny/manager/client.go
One of our customers observed that we have a memory leak in our services. Looking at the memory usage for the controller, distributor, manager we could see how the memory spikes above the requested limit, and then the pods will eventually restart. 
We did profile the controller, distributor, manager and we observed that large chunk of the allocated heap has been due to TLS stuff which seems to be an indication that we may not create http connections properly. 
Our HTTP clients when using TLS have disable keep alive (which means the underlying http connections should be reused). We looked at the number of new, idle, and closed connections over time for each service, and we found out that we kept creating new connections instead of reusing them. 
We tried many things, but one thing that we …
=> Memory leak fix

internal/config/config.pb.go, internal/config/config.proto, internal/gke/gke.go, internal/gke/logging.go, internal/gke/nanny.go, internal/tool/deploy.go, internal/tool/deploy_test.go
Right now we export all the logs to the Google Cloud Logging. However, this can significantly impact the cloud bill.
This PR provides an optional logging knob to the user to specify the minimum level for a log entry to be exported to the Google Cloud Logging. Note that this option only applies to application logs. We'll continue to export all the services logs (e.g., controller, distributor, manager logs).
By default all app logs are exported. However, if the user wants to set a minimum log level for exporting logs, they can modify their gke config as follows:
weaver.toml
`
...
[gke]
telemetry.logging = {min_export_level = "WARN"}
...
`
This will export all logs with the level at least WARN, i.e., WARN and ERROR.
=> Add logging knobs in the config
